project_id = "vxvngoccmbyjyjlbzpbt"

[functions.analyze-goal]
verify_jwt = false

[functions.delete-account]
verify_jwt = true

[functions.redeem-promo-code]
verify_jwt = false

[functions.create-razorpay-order]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

